[book]
authors = ["Hamza Jadid"]
language = "en"
multilingual = false
src = "src"
title = "Yet Another Rust Book"

[output.html]
git-repository-url = "https://github.com/ghamza-rust/ghamza-rust.github.io"
git-repository-icon = "fa-github"
cname = "rust-book.ghamza.dev"

[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
use-data-uris = true
